-- MySQL Script generated by MySQL Workbench
-- Thứ ba, 12 Tháng mười hai Năm 2017 08:37:53 +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema file_share
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `file_share` ;

-- -----------------------------------------------------
-- Schema file_share
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `file_share` DEFAULT CHARACTER SET utf8 ;
USE `file_share` ;

-- -----------------------------------------------------
-- Table `file_share`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `file_share`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `file_share`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `file_share`.`files` (
  `file_id` INT NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(45) NULL,
  `share_type` INT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`file_id`),
  INDEX `fk_files_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_files_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `file_share`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

select * from users;
select * from files;
SELECT u.username, f.filename, f.share_type FROM users u JOIN files f WHERE u.user_id = f.user_id;
SELECT u.username, f.filename FROM users u JOIN files f WHERE u.username = 'ha' AND f.filename = 'testha.pdf' AND f.share_type = 3 AND u.user_id = f.user_id

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

